---
- name: Create Traefik configuration directory
  file:
    path: "{{ app_dir }}/traefik"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create acme.json file for Let's Encrypt certificates
  file:
    path: "{{ app_dir }}/traefik/acme.json"
    state: touch
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Create Traefik configuration file
  copy:
    dest: "{{ app_dir }}/traefik/traefik.toml"
    content: |
      [global]
        checkNewVersion = true
        sendAnonymousUsage = false

      [log]
        level = "INFO"

      [entryPoints]
        [entryPoints.web]
          address = ":80"
          [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

        [entryPoints.websecure]
          address = ":443"

        [entryPoints.dashboard]
          address = ":8080"

      [api]
        dashboard = true
        insecure = true

      [providers]
        [providers.docker]
          endpoint = "unix:///var/run/docker.sock"
          watch = true
          exposedByDefault = false

      [certificatesResolvers.letsencrypt.acme]
        email = "{{ email }}"
        storage = "acme.json"
        [certificatesResolvers.letsencrypt.acme.tlsChallenge]
    owner: ubuntu
    group: ubuntu
    mode: '0644'